### ISSUE TITLE
遇到的几个问题

### ISSUE THREAD

**Issue by DVLZY** [h-dj/yuque2md#1]
1. GPK 编码报错,指定编码  `with open( file_name, 'r', encoding='utf-8') as f:`
2.部分图片URL无法正常识别文件名称,可以使用MD5进行重命名 `image_file_name = hashlib.md5(image_src.encode(encoding='UTF-8')).hexdigest() + '.jpg'` 
3. 发现无法导出日历卡片和文件附件
4. 参数获取方式如下 
-  login 取自语雀个人主页URL中特征部分 例如 `https://www.yuque.com/cxxxhela-axxxx` 中的  `cxxxhela-axxxx`
-  token 在该页面中申请 https://www.yuque.com/settings/tokens

> 第一次提ISSUES不太了解格式,还请谅解,如有不对还请指正

**Comment by h-dj** [comment]
导出日历卡片和文件附件暂时不考虑，目前只考虑离线图片。 编码问题和部分图片URL无法正常识别文件名称修改了
